export const place = [
    {value: 'podgorica', label: 'Podgorica'},
    {value: 'nikšić', label: 'Nikšić'},
    {value: 'kotor', label: 'Kotor'},
    {value: 'herceg hovi', label: 'Herceg Novi'},
    {value: 'pljevlja', label: 'Pljevlja'},
    {value: 'bar', label: 'Bar'},
    {value: 'budva', label: 'Budva'},
    {value: 'bijelo polje', label: 'Bijelo Polje'},
    {value: 'cetinje', label: 'Cetinje'},
    {value: 'berane', label: 'Berane'},
    {value: 'ulcinj', label: 'Ulcinj'},
    {value: 'tivat', label: 'Tivat'},
    {value: 'rožaje', label: 'Rožaje'},
    {value: 'dobrota', label: 'Dobrota'},
    {value: 'danilovgrad', label: 'Danilovgrad'},
    {value: 'plav', label: 'Plav'},
    {value: 'burtaiši', label: 'Brtaiši'},
    {value: 'Škaljari', label: 'Škaljari'},
    {value: 'mojkovac', label: 'Mojkovac'},
    {value: 'tuzi', label: 'Tuzi'},
    {value: 'igalo', label: 'Igalo'},
    {value: 'bijela', label: 'Bijela'},
    {value: 'zabljak', label: 'Žabljak'},
    {value: 'ibarac', label: 'Ibarac'},
    {value: 'golubovci', label: 'Golubovci'},
    {value: 'resnik', label: 'Resnik'},
    {value: 'kolasin', label: 'Kolašin'},
    {value: 'susanj', label: 'Šušanj'},
    {value: 'mojanovici', label: 'Mojanovići'},
    {value: 'nedakusi', label: 'Nedakusi'},
    {value: 'mrcevac', label: 'Mrčevac'},
    {value: 'risan', label: 'Risan'},
    {value: 'ozrinci', label: 'Mojanovići'},
    {value: 'budimlja', label: 'Budimlja'},
    {value: 'sutomore', label: 'Sutomore'},
    {value: 'pokrajci', label: 'Pokrajci'},
    {value: 'pesca', label: 'Pešca'},
    {value: 'polje', label: 'Polje'},
    {value: 'stari bar', label: 'Stari Bar'},
    {value: 'donje luge', label: 'Donje Luge'},
    {value: 'beran selo', label:'Beran Selo'},
    {value: 'bijelisi', label:'Bjeliši'},
    {value: 'spuz', label:'Bjeliši'},
    {value: 'gusinje', label:'Gusinje'},
    {value: 'ljesnica', label:'Lješnica'},
    {value: 'celuga', label:'Čeluga'},
    {value: 'goricani', label:'Goričani'},
    {value: 'zelenika', label:'Zelenika'},
    {value: 'dolac', label:'Dolac'},
    {value: 'petrovac', label:'Petrovac'},
    {value: 'podi', label:'Podi'},
    {value: 'pluzine', label:'Plužine'},
    {value: 'mahal', label:'Mahala'},
    {value: 'mataguzi', label:'Mataguži'},
    {value: 'baosici', label:'Baošići'},
    {value: 'polja', label:'Polja'},
    {value: 'tomba', label:'Tomba'},
    {value: 'djenovici', label:'Đenovići'},
    {value: 'prcanje', label:'Prčanj'},
    {value: 'meljine', label:'Meljine'},
    {value: 'andrijevica', label:'Andrijevica'},
    {value: 'kodre', label:'Kodre'},
    {value: 'buce', label:'Buče'},
    {value: 'kumbor', label:'Kumbor'},
    {value: 'becici', label:'Bečići'},
    {value: 'smajlagica polje', label:'Smajlagića Polje'},
    {value: 'donja lastva', label:'Donja Lastva'},
    {value: 'zidovici', label:'Židovići'},
    {value: 'savnik', label:'Šavnik'},
    {value: 'slatina', label:'Slatina'},
    {value: 'sveti stefan', label:'Sveti Stefan'},
    {value: 'gradac', label:'Gradac'},
    {value: 'virpazar', label:'Virpazar'},
    {value: 'perast', label:'Perast'},
    {value: 'goransko', label:'Goransko'},
    {value: 'bare', label:'Bare'},
    {value: 'njegovudja', label:'Njegovuđa'},
    {value: 'rijeka crnojenica', label:'Rijeka Crnojevića'}
  ]

export const subject = [
    {value: 'mathematics', label: 'Mathematics'},
    {value: 'english', label: 'English'},
    {value: 'russian', label: 'Russian'},
    {value: 'italian', label: 'Italian'},
    {value: 'german', label: 'German'},
    {value: 'french', label: 'French'},
    {value: 'informatics', label: 'Informatics'}
]

export const school = [
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''},
    {value: '', label: ''}
]
  